apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-to-pdf-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doc-to-pdf
  template:
    metadata:
      labels:
        app: doc-to-pdf
    spec:
      containers:
      - name: doc-to-pdf
        image: doc-to-pdf:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: doc-to-pdf-service
spec:
  selector:
    app: doc-to-pdf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
